### ISSUE TITLE
Compute Metacells with different Reduction

### ISSUE THREAD

**Issue by shahrozeabbas** [cantinilab/Circe#2]
Hi,

Good to see this has come a long way since `atacnet`!

Quick question, just wondering if the option to provide a different reduction than `lsi` would be implemented at some point?

Thanks,
Shahroze

**Comment by r-trimbour** [comment]
Hi Shahroze,

You can now use your own dimensionality reduction stored in `adata.obsm["dim_reduction"]` to compute the metacells:
```
>>> data = sc.read_h5ad("data/test2.h5ad")
AnnData object with n_obs × n_vars = 500 × 9928
    uns: 'gene_activities_names'
    obsm: 'gene_activities'
```
```
>>> metacells = circe.metacells.compute_metacells(data, dim_reduction="gene_activities")
Using adata.obsm['gene_activities'] to identify neighboring cells
Computing metacells... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
```

You can get this version from `pip install circe-py==0.3.3`, or from the `dev branch` of this repo.
I might additional implement other reduction method internally to Circe, but it's not planned yet.

Finally, you can also compute your own metacells from external methods and use `circe.compute_atac_network` directly on these metacells.


Let me know if it matches your needs regarding Circe use. :)
Rémi

**Comment by r-trimbour** [comment]
Quick update: I have some problem when uploading the package to pip.
Will make some changes and update a version `circe-py==0.3.4`.
Tagging you as soon as it's done.

**Comment by shahrozeabbas** [comment]
No worries! Thanks for making the changes, look forward to trying it out.

**Comment by r-trimbour** [comment]
The version described above is available :)
`pip install circe-py==0.3.4 --upgrade`

**Comment by shahrozeabbas** [comment]
Hi,

Just tried installing the new update in a `conda` environment and it looks like something is going wrong. Is this on my end?

```
      building 'circe.pyquic' extension
      creating build/temp.linux-x86_64-cpython-39/pyquic_ext
      gcc -pthread -B /data/abbass2/miniforge3/envs/circe/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /data/abbass2/miniforge3/envs/circe/include -fPIC -O2 -isystem /data/abbass2/miniforge3/envs/circe/include -fPIC -Ipyquic_ext -I/tmp/pip-build-env-m80v97sr/overlay/lib/python3.9/site-packages/numpy/core/include -I/usr/local/include -I/tmp/pip-build-env-m80v97sr/overlay/lib/python3.9/site-packages/numpy/core/include -I/data/abbass2/miniforge3/envs/circe/include/python3.9 -c pyquic_ext/QUIC.C -o build/temp.linux-x86_64-cpython-39/pyquic_ext/QUIC.o -msse2 -O2 -fPIC -w
      g++ -pthread -B /data/abbass2/miniforge3/envs/circe/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /data/abbass2/miniforge3/envs/circe/include -fPIC -O2 -isystem /data/abbass2/miniforge3/envs/circe/include -fPIC -Ipyquic_ext -I/tmp/pip-build-env-m80v97sr/overlay/lib/python3.9/site-packages/numpy/core/include -I/usr/local/include -I/tmp/pip-build-env-m80v97sr/overlay/lib/python3.9/site-packages/numpy/core/include -I/data/abbass2/miniforge3/envs/circe/include/python3.9 -c pyquic_ext/pyquic.cpp -o build/temp.linux-x86_64-cpython-39/pyquic_ext/pyquic.o -msse2 -O2 -fPIC -w
      g++ -pthread -B /data/abbass2/miniforge3/envs/circe/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /data/abbass2/miniforge3/envs/circe/include -fPIC -O2 -isystem /data/abbass2/miniforge3/envs/circe/include -pthread -B /data/abbass2/miniforge3/envs/circe/compiler_compat -shared build/temp.linux-x86_64-cpython-39/pyquic_ext/QUIC.o build/temp.linux-x86_64-cpython-39/pyquic_ext/pyquic.o -llapack -lblas -o build/lib.linux-x86_64-cpython-39/circe/pyquic.cpython-39-x86_64-linux-gnu.so -llapack
      /data/abbass2/miniforge3/envs/circe/compiler_compat/ld: cannot find -llapack: No such file or directory
      /data/abbass2/miniforge3/envs/circe/compiler_compat/ld: cannot find -lblas: No such file or directory
      /data/abbass2/miniforge3/envs/circe/compiler_compat/ld: cannot find -llapack: No such file or directory
      collect2: error: ld returned 1 exit status
      error: command '/usr/bin/g++' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for circe-py
  Building wheel for session-info (setup.py) ... done
  Created wheel for session-info: filename=session_info-1.0.0-py3-none-any.whl size=8023 sha256=29334f5761c09fa2d8b2291fc1e029d23a0da6a00cc68de93140a8ac9032cd46
  Stored in directory: /gpfs/gsfs12/users/abbass2/.pipcache/wheels/d4/fc/2e/00ca60bac7954b84907efd41baa9b4853500eaeec4228410c6
Successfully built session-info
Failed to build circe-py
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (circe-py)
(circe) [abbass2@cn0039:~]$ 

```

**Comment by r-trimbour** [comment]
By running this you should have everything needed:
`conda install conda-forge::lapack`
`conda install gxx_linux-64`

**Comment by shahrozeabbas** [comment]
Looks like there's another following the installation of the two above.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/abbass2/miniforge3/envs/circe/lib/python3.9/site-packages/circe/__init__.py", line 1, in <module>
    from circe.circe import extract_atac_links, \
  File "/data/abbass2/miniforge3/envs/circe/lib/python3.9/site-packages/circe/circe.py", line 6, in <module>
    from circe import quic_graph_lasso
  File "/data/abbass2/miniforge3/envs/circe/lib/python3.9/site-packages/circe/quic_graph_lasso.py", line 18, in <module>
    import circe.pyquic
ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory
```


I have `libgfortran` installed in the conda environment.

**Comment by shahrozeabbas** [comment]
> Looks like there's another following the installation of the two above.
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/data/abbass2/miniforge3/envs/circe/lib/python3.9/site-packages/circe/__init__.py", line 1, in <module>
>     from circe.circe import extract_atac_links, \
>   File "/data/abbass2/miniforge3/envs/circe/lib/python3.9/site-packages/circe/circe.py", line 6, in <module>
>     from circe import quic_graph_lasso
>   File "/data/abbass2/miniforge3/envs/circe/lib/python3.9/site-packages/circe/quic_graph_lasso.py", line 18, in <module>
>     import circe.pyquic
> ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory
> ```
> 
> I have `libgfortran` installed in the conda environment.

Also the above is after installation of the package is successful. This occurs during the import step.

**Comment by r-trimbour** [comment]
It might be worth checking your `libfortran` version in the 2 different environments or to try running `conda install libfortran=3`.

I can't check right now, but if it doesn't help, I'll upload the conda yaml file of my current HPC environment, maybe we can see the difference then
